"""initial_schema

Revision ID: 1e7b550f04b7
Revises: 
Create Date: 2026-02-21 08:59:43.891016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e7b550f04b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vote_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vote_snapshots_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vote_snapshots_video_id'))

    op.drop_table('vote_snapshots')
    # ### end Alembic commands ###
